# fly.toml app configuration file generated for langroid-cloud-app-lively-feather-573 on 2024-10-31T09:40:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langroid-cloud-app-lively-feather-573'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
